[package]
name = "cantor_ecosystem"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
cantor_core = { path = "../cantor_core" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
ed25519-dalek.workspace = true

[lints]
workspace = true
