[CmdletBinding()]
param([string]$OutputPath = 'experiments/provider_free_release_signature_verification/release_signature_evidence_manifest.json')

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$root = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$evidence = Get-Content -LiteralPath (Join-Path $root 'experiments/provider_free_release_signature_verification/artifacts/release_signature_evidence_v1.json') -Raw | ConvertFrom-Json
$paths = @(
    'Cargo.toml','Cargo.lock','crates/cantor_release_signature/Cargo.toml','crates/cantor_release_signature/src/lib.rs','crates/cantor_release_signature/src/main.rs','crates/cantor_release_signature/examples/generate_release_signature_fixture.rs','crates/cantor_release_signature/tests/release_signature.rs','crates/cantor_release_signature/tests/release_signature_cli.rs',
    'scripts/build_cantor_provider_free_release_signature_evidence.ps1','scripts/verify_cantor_provider_free_release_signature_evidence.ps1','scripts/test_cantor_provider_free_release_signature_evidence.ps1','scripts/build_cantor_provider_free_release_signature_evidence_manifest.ps1',
    'experiments/provider_free_release_signature_verification/README.md','experiments/provider_free_release_signature_verification/artifacts/release_signature_policy_synthetic_v1.json','experiments/provider_free_release_signature_verification/artifacts/release_signature_envelope_synthetic_v1.json','experiments/provider_free_release_signature_verification/artifacts/release_signature_receipt_synthetic_v1.json','experiments/provider_free_release_signature_verification/artifacts/cantor-release-verify-linux-x86_64','experiments/provider_free_release_signature_verification/artifacts/release_signature_evidence_v1.json',
    'docs/PROVIDER_FREE_RELEASE_SIGNATURE_VERIFICATION_P0.md','source_documents/2026-08-23_provider_free_release_signature_verification_p0/Cantor_Provider_Free_Release_Signature_Verification_P0_Source.sop','source_documents/2026-08-23_provider_free_release_signature_verification_p0/manifest.sop','specifications/Cantor_Provider_Free_Release_Signature_Verification_P0.sop','specifications/exploded/Cantor_Provider_Free_Release_Signature_Verification_P0.exploded.sop','narrative/research/Cantor_Provider_Free_Release_Signature_Verification_P0_SJS_Review_2026-08-23.sop','plans/Cantor_Provider_Free_Release_Signature_Verification_P0_Plan.sop','feature_support/Cantor_Provider_Free_Release_Signature_Verification_P0_Requirement_Matrix.sop','narrative/registries/Cantor_Provider_Free_Release_Signature_Verification_P0_Phase_Lock.sop','narrative/turns/1787490000000_provider_free_release_signature_verification_p0_activation.sop',
    'solutions/Cantor_Provider_Free_Release_Signature_Verification_P0_Solution.sop','proofs/Cantor_Provider_Free_Release_Signature_Verification_P0_Proof.sop','narrative/research/Cantor_Provider_Free_Release_Signature_Verification_P0_Completion_Review_2026-08-23.sop','narrative/reentry/Cantor_Provider_Free_Release_Signature_Verification_P0_Reentry.sop','narrative/operational_faults/1787492000000_provider_free_release_signature_verification_p0_faults.sop','narrative/turns/1787492000000_provider_free_release_signature_verification_p0_completion.sop','narrative/file_changes/1787492000000_provider_free_release_signature_verification_p0_file_change.sop',
    'docs/CANTOR_PRODUCT_READINESS_2026-08-23.md','feature_support/Cantor_Product_Readiness_2026_08_23_Requirement_Matrix.sop','feature_support/Cantor_Engine_Build_Slice_Index.sop','narrative/Project_Narrative.sop','README.md','experiments/provider_free_portable_release_bundle/artifacts/portable_release_bundle_evidence_manifest.json','proofs/Cantor_Provider_Free_Portable_Release_Bundle_P0_Proof.sop'
)
$artifacts = foreach($relative in $paths){$item=Get-Item -LiteralPath (Join-Path $root $relative) -Force; if($item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0){throw "manifest input is not physical: $relative"}; [ordered]@{path=$relative.Replace('\','/');bytes=[uint64]$item.Length;sha256=(Get-FileHash -LiteralPath $item.FullName -Algorithm SHA256).Hash}}
$manifest=[ordered]@{profile='cantor-provider-free-release-signature-evidence-manifest/0.1';evidence_manifest_uuid='dd6282ac-4c5b-424d-b80c-6970c7810a25';source_commit=[string]$evidence.source_commit;generated_at_utc=[DateTime]::UtcNow.ToString('o');artifacts=@($artifacts);non_authority_statement='This manifest binds public synthetic detached-signature mechanics and grants no policy governance publisher authenticity trust delivery installation secret service provider effect or production authority.'}
$output=if([IO.Path]::IsPathRooted($OutputPath)){[IO.Path]::GetFullPath($OutputPath)}else{[IO.Path]::GetFullPath((Join-Path $root $OutputPath))}
[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($output))|Out-Null
[IO.File]::WriteAllText($output,"$(($manifest|ConvertTo-Json -Depth 100).Replace("`r`n","`n"))`n",[Text.UTF8Encoding]::new($false))
Write-Output $output
