#requires -Version 7.6
param([Parameter(Mandatory)][string]$PackageLeaf,[Parameter(Mandatory)][string]$EvidenceLeaf)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'lib/Cantor_Inspection_Runtime_Seed_P0_Common.ps1')
& (Join-Path $PSScriptRoot 'verify_cantor_inspection_runtime_seed_p0.ps1') -PackageLeaf $PackageLeaf
$leaf=Assert-SeedLeaf $EvidenceLeaf -Create
$positiveZip=Read-SeedBounded (Join-Path $PackageLeaf 'cantor-inspection-runtime-seed-windows-x86_64-p0.zip') 16777216
$positiveReport=Read-SeedBounded (Join-Path $PackageLeaf 'seed-report.json') 131072
$positive=$script:SeedUtf8.GetString($positiveReport)|ConvertFrom-Json -AsHashtable
$script:Refusals=[Collections.Generic.List[object]]::new()
function New-MutationLeaf {return Assert-SeedLeaf ('D:\CantorBuilds\cantor-inspection-seed\seed-'+[guid]::NewGuid().ToString('N')) -Create}
function Test-Refusal([string]$Name,[scriptblock]$Action) {
    $refused=$false;$fault=''
    try {& $Action|Out-Null} catch {$refused=$true;$fault=$_.Exception.Message}
    if(-not $refused){throw ('seed_adversary_was_accepted:'+ $Name)}
    if($fault -cnotmatch '^seed_'){throw ('seed_adversary_harness_fault:'+ $Name+':'+$fault)}
    $script:Refusals.Add([ordered]@{case=$Name;refused=$true;fault=$fault})
}
function Invoke-Mutant([byte[]]$Zip,[byte[]]$Report) {
    $mutant=New-MutationLeaf
    Write-SeedNew (Join-Path $mutant 'cantor-inspection-runtime-seed-windows-x86_64-p0.zip') $Zip
    Write-SeedNew (Join-Path $mutant 'seed-report.json') $Report
    & (Join-Path $PSScriptRoot 'verify_cantor_inspection_runtime_seed_p0.ps1') -PackageLeaf $mutant
}
function Set-Word([byte[]]$Zip,[int]$Offset,[uint32]$Value,[int]$Width) {
    $bytes=if($Width -eq 2){[BitConverter]::GetBytes([uint16]$Value)}else{[BitConverter]::GetBytes($Value)}
    [Array]::Copy($bytes,0,$Zip,$Offset,$Width)
}
# Known CRC vector is not generated by the archive writer.
if((Get-SeedCrc ([Text.Encoding]::ASCII.GetBytes('123456789'))) -ne [uint32]3421780262){throw 'seed_crc_vector'}
$second='D:\CantorBuilds\cantor-inspection-seed\seed-'+[guid]::NewGuid().ToString('N')
$inherited=@{}
foreach($key in @('CARGO_BUILD_TARGET','CARGO_ENCODED_RUSTFLAGS','RUSTC_WRAPPER','RUSTC_WORKSPACE_WRAPPER')){$inherited[$key]=[Environment]::GetEnvironmentVariable($key,'Process')}
try {
    $env:CARGO_BUILD_TARGET='unexpected-unknown-unknown';$env:CARGO_ENCODED_RUSTFLAGS='invalid_flag_should_not_be_used'
    $env:RUSTC_WRAPPER='D:\CantorBuilds\nonexistent-wrapper.exe';$env:RUSTC_WORKSPACE_WRAPPER='D:\CantorBuilds\nonexistent-workspace-wrapper.exe'
    & (Join-Path $PSScriptRoot 'build_cantor_inspection_runtime_seed_p0.ps1') -OutputLeaf $second
    if($env:CARGO_BUILD_TARGET -cne 'unexpected-unknown-unknown' -or $env:CARGO_ENCODED_RUSTFLAGS -cne 'invalid_flag_should_not_be_used' -or $env:RUSTC_WRAPPER -cne 'D:\CantorBuilds\nonexistent-wrapper.exe' -or $env:RUSTC_WORKSPACE_WRAPPER -cne 'D:\CantorBuilds\nonexistent-workspace-wrapper.exe'){throw 'seed_build_environment_not_restored'}
} finally {
    foreach($key in $inherited.Keys){
        if($null -eq $inherited[$key]){Remove-Item -LiteralPath ('Env:'+ $key) -ErrorAction SilentlyContinue}
        else {Set-Item -LiteralPath ('Env:'+ $key) -Value $inherited[$key]}
    }
}
foreach($key in $inherited.Keys){if([Environment]::GetEnvironmentVariable($key,'Process') -cne $inherited[$key]){throw 'seed_original_environment_not_restored'}}
$secondZip=Read-SeedBounded (Join-Path $second 'cantor-inspection-runtime-seed-windows-x86_64-p0.zip') 16777216
$secondReport=Read-SeedBounded (Join-Path $second 'seed-report.json') 131072
if(-not(Test-SeedBytes $positiveZip $secondZip) -or -not(Test-SeedBytes $positiveReport $secondReport)){throw 'seed_same_input_determinism'}
Test-Refusal 'existing_output' {& (Join-Path $PSScriptRoot 'build_cantor_inspection_runtime_seed_p0.ps1') -OutputLeaf $PackageLeaf}
Test-Refusal 'outside_output' {Assert-SeedLeaf 'C:\Project\Cantor\seed-00000000000000000000000000000000' -Create}
Test-Refusal 'escaping_output' {Assert-SeedLeaf 'D:\CantorBuilds\cantor-inspection-seed\..\seed-00000000000000000000000000000000' -Create}
foreach($coordinate in @(@('source_bound',8192),@('request_bound',65536),@('argument_example_bound',131072))) {
    $boundedPath=Join-Path $leaf ($coordinate[0]+'.bin')
    Write-SeedNew $boundedPath ([byte[]]::new($coordinate[1]+1))
    Test-Refusal $coordinate[0] {Read-SeedBounded $boundedPath $coordinate[1]}
}
$end=$positiveZip.Length-22;$central=[int][BitConverter]::ToUInt32($positiveZip,$end+16)
$headerCases=@(
    @('local_signature',0,0,4),@('local_version',4,21,2),@('local_encryption_flag',6,2049,2),@('local_descriptor_flag',6,2056,2),
    @('local_store_method',8,8,2),@('local_timestamp',10,1,2),@('local_date',12,34,2),@('local_crc',14,0,4),
    @('local_size',18,8388609,4),@('local_extra_field',28,1,2),
    @('central_store_method',($central+10),8,2),@('central_crc',($central+16),0,4),@('central_comment',($central+32),1,2),
    @('central_attributes',($central+38),1,4),@('central_local_offset',($central+42),1,4),
    @('end_split_disk',($end+4),1,2),@('end_entry_count',($end+10),8,2),@('end_directory_offset',($end+16),1,4),@('end_comment',($end+20),1,2)
)
foreach($case in $headerCases) {
    $mutant=[byte[]]$positiveZip.Clone();Set-Word $mutant $case[1] $case[2] $case[3]
    $report=$positiveReport.Clone()
    # Update outer archive identity: refusals must come from raw framing, not stale hash.
    $object=$script:SeedUtf8.GetString($report)|ConvertFrom-Json -AsHashtable
    $object.archive_sha256=Get-SeedSha $mutant
    $report=$script:SeedUtf8.GetBytes((ConvertTo-SeedCanonical $object)+"`n")
    Test-Refusal $case[0] {Invoke-Mutant $mutant $report}
}
foreach($name in @('rooted_entry','traversal_entry','nonascii_entry')) {
    $mutant=[byte[]]$positiveZip.Clone()
    $replacement=switch($name){rooted_entry {'/UIDE.md'} traversal_entry {'../DE.md'} nonascii_entry {'GUIDE.m?'}}
    $raw=$script:SeedUtf8.GetBytes($replacement)
    [Array]::Copy($raw,0,$mutant,30,8);[Array]::Copy($raw,0,$mutant,$central+46,8)
    if($name -ceq 'nonascii_entry'){$mutant[37]=255;$mutant[$central+53]=255}
    Test-Refusal $name {Invoke-Mutant $mutant $positiveReport}
}
$duplicateStream=[IO.MemoryStream]::new()
$duplicateZip=[IO.Compression.ZipArchive]::new($duplicateStream,[IO.Compression.ZipArchiveMode]::Create,$true,$script:SeedUtf8)
$payloads=Get-SeedPayloads
try {
    for($index=0;$index -lt 7;$index++) {
        $name=$script:SeedNames[$index]
        $duplicateName=if($index -eq 1){'GUIDE.md'}else{$name}
        $entry=$duplicateZip.CreateEntry($duplicateName,[IO.Compression.CompressionLevel]::NoCompression)
        $entry.LastWriteTime=[DateTimeOffset]::new(1980,1,1,0,0,0,[TimeSpan]::Zero);$entry.ExternalAttributes=0
        $body=$entry.Open();try{$body.Write([byte[]]$payloads[$name])}finally{$body.Dispose()}
    }
} finally {$duplicateZip.Dispose()}
$duplicateBytes=$duplicateStream.ToArray();$duplicateStream.Dispose()
Test-Refusal 'duplicate_entry' {Invoke-Mutant $duplicateBytes $positiveReport}
$swappedStream=[IO.MemoryStream]::new()
$swappedZip=[IO.Compression.ZipArchive]::new($swappedStream,[IO.Compression.ZipArchiveMode]::Create,$true,$script:SeedUtf8)
try {
    $swappedNames=@($script:SeedNames);$swappedNames[0]=$script:SeedNames[1];$swappedNames[1]=$script:SeedNames[0]
    foreach($name in $swappedNames) {
        $entry=$swappedZip.CreateEntry($name,[IO.Compression.CompressionLevel]::NoCompression)
        $entry.LastWriteTime=[DateTimeOffset]::new(1980,1,1,0,0,0,[TimeSpan]::Zero);$entry.ExternalAttributes=0
        $body=$entry.Open();try{$body.Write([byte[]]$payloads[$name])}finally{$body.Dispose()}
    }
} finally {$swappedZip.Dispose()}
$swappedBytes=$swappedStream.ToArray();$swappedStream.Dispose()
Test-Refusal 'entry_order' {Invoke-Mutant $swappedBytes $positiveReport}
$trailing=[byte[]]::new($positiveZip.Length+1);[Array]::Copy($positiveZip,$trailing,$positiveZip.Length)
Test-Refusal 'archive_trailing_octet' {Invoke-Mutant $trailing $positiveReport}
$overZip=[byte[]]::new(16777217)
Test-Refusal 'archive_bound' {Invoke-Mutant $overZip $positiveReport}
$overReport=[byte[]]::new(131073)
Test-Refusal 'report_bound' {Invoke-Mutant $positiveZip $overReport}
$duplicate=$script:SeedUtf8.GetString($positiveReport).Replace('"entry_count":7','"entry_count":7,"entry_count":7')
Test-Refusal 'raw_duplicate_report_field' {Invoke-Mutant $positiveZip $script:SeedUtf8.GetBytes($duplicate)}
Test-Refusal 'trailing_report_json' {Invoke-Mutant $positiveZip $script:SeedUtf8.GetBytes($script:SeedUtf8.GetString($positiveReport)+"{}")}
foreach($name in @('unknown_field','wrong_source','wrong_formation','wrong_target','wrong_scope','wrong_lock','entry_membership','entry_digest','archive_digest','field_type','field_order')) {
    $object=$script:SeedUtf8.GetString($positiveReport)|ConvertFrom-Json -AsHashtable
    switch($name) {
        unknown_field {$object['future_effect_authority']=$true}
        wrong_source {$object.source_commit=('0'*40)}
        wrong_formation {$object.formation_commit=('0'*40)}
        wrong_target {$object.target='aarch64-unknown-linux-gnu'}
        wrong_scope {$object.non_authority='authorized autonomous agent'}
        wrong_lock {$object.cargo_lock_sha256=('0'*64)}
        entry_membership {$object.entries[0].path='foreign'}
        entry_digest {$object.entries[0].sha256=('0'*64)}
        archive_digest {$object.archive_sha256=('0'*64)}
        field_type {$object.entry_count='7'}
    }
    $raw=$script:SeedUtf8.GetBytes((ConvertTo-SeedCanonical $object)+"`n")
    if($name -ceq 'field_order') {
        $raw=$script:SeedUtf8.GetBytes('{"entry_count":7,'+$script:SeedUtf8.GetString($raw).Replace('"entry_count":7,','').Substring(1))
    }
    Test-Refusal $name {Invoke-Mutant $positiveZip $raw}
}
# Change payloads and repair every manifest/report identity and both ZIP CRC
# headers. Even a fully internally consistent claim cannot replace source bytes.
foreach($targetName in @('bin/cantor-sop-inspect-mcp.exe','sop/seed.sop')) {
    $changedPayloads=Get-SeedPayloads
    $changedPayloads[$targetName]=[byte[]]$changedPayloads[$targetName].Clone()
    $changedPayloads[$targetName][200]=$changedPayloads[$targetName][200] -bxor 1
    if($targetName -ceq 'sop/seed.sop') {
        $changedWire=$script:SeedUtf8.GetString($changedPayloads['examples/inspect-seed-request.json'])|ConvertFrom-Json -AsHashtable
        $changedWire.request.project.packages[0].files[0].text=$script:SeedUtf8.GetString($changedPayloads[$targetName])
        $changedWire.request.request_digest=''
        $changedWire.request.request_digest=(Get-SeedSha $script:SeedUtf8.GetBytes('cantor-sop-semantic-inspection-request/0.1'+[char]0+(ConvertTo-SeedCanonical $changedWire.request))).ToLowerInvariant()
        $changedWireText=ConvertTo-SeedCanonical $changedWire
        $changedPayloads['examples/inspect-seed-request.json']=$script:SeedUtf8.GetBytes($changedWireText+"`n")
        $changedPayloads['examples/mcp-tool-arguments.json']=$script:SeedUtf8.GetBytes((ConvertTo-SeedCanonical @{wire_request_json=$changedWireText})+"`n")
    }
    $changedManifest=$script:SeedUtf8.GetString($changedPayloads['seed-manifest.json'])|ConvertFrom-Json -AsHashtable
    foreach($inputIdentity in $changedManifest.inputs) {
        $inputIdentity.bytes=$changedPayloads[$inputIdentity.path].Length
        $inputIdentity.sha256=Get-SeedSha $changedPayloads[$inputIdentity.path]
    }
    $changedPayloads['seed-manifest.json']=$script:SeedUtf8.GetBytes((ConvertTo-SeedCanonical $changedManifest)+"`n")
    $mutant=[byte[]]$positiveZip.Clone();$local=0;$directory=$central
    $object=$script:SeedUtf8.GetString($positiveReport)|ConvertFrom-Json -AsHashtable
    foreach($entry in $positive.entries) {
        $nameLen=$script:SeedUtf8.GetByteCount($entry.path);$start=$local+30+$nameLen
        $changed=$changedPayloads[$entry.path]
        if($changed.Length -ne $entry.bytes){throw 'seed_adversarial_size_drift'}
        [Array]::Copy($changed,0,$mutant,$start,$changed.Length)
        $crc=Get-SeedCrc $changed;Set-Word $mutant ($local+14) $crc 4;Set-Word $mutant ($directory+16) $crc 4
        $object.entries|Where-Object {$_.path -ceq $entry.path}|ForEach-Object {$_.crc32=$crc;$_.sha256=Get-SeedSha $changed}
        $local=$start+$entry.bytes;$directory+=46+$nameLen
    }
    $object.archive_sha256=Get-SeedSha $mutant
    $raw=$script:SeedUtf8.GetBytes((ConvertTo-SeedCanonical $object)+"`n")
    Test-Refusal ('self_consistent_payload_drift:'+ $targetName) {Invoke-Mutant $mutant $raw}
}
$report=[ordered]@{
    profile='cantor-inspection-runtime-seed-adversarial-test/0.1';positive_archive_bytes=$positiveZip.Length;positive_archive_sha256=Get-SeedSha $positiveZip
    same_input_generations=2;archive_byte_equality=$true;report_byte_equality=$true;crc_known_vector=3421780262
    inherited_build_environment_normalized=$true;process_build_environment_restored=$true
    refusal_count=$script:Refusals.Count;refusals=$script:Refusals.ToArray();producer_runtime_launches=0;verifier_runtime_launches=0;extractions=0
    provider_trials=0;remote_calls=0;non_authority=$script:SeedDenials
}
Write-SeedNew (Join-Path $leaf 'adversarial-test-report.json') $script:SeedUtf8.GetBytes((ConvertTo-SeedCanonical $report)+"`n")
Write-Output ('cantor_seed_adversaries_passed=true refusals='+$script:Refusals.Count+' deterministic_generations=2 evidence='+$leaf)
