[CmdletBinding()]
param([string]$Root = '',[switch]$RequireBookend)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
if([string]::IsNullOrWhiteSpace($Root)){$Root=Split-Path -Parent $PSScriptRoot}
$rootPath=(Resolve-Path -LiteralPath $Root).Path
$manifest=Get-Content -LiteralPath (Join-Path $rootPath 'experiments/evox2_remote_preflight_one_shot_activation_ceremony_p0/private_permit_bridge_formation_publication_evidence_manifest.json') -Raw|ConvertFrom-Json
if($manifest.profile -cne 'cantor-evox2-remote-preflight-private-permit-bridge-formation-publication-evidence/0.1' -or $manifest.manifest_uuid -cne '894a0b3c-21a4-4e32-96cc-a82c7fb57bea' -or $manifest.canonical_uuid -cne '06d82d16-143a-4abb-9c70-c03163285842' -or $manifest.publication_proof_uuid -cne 'af0f674b-8ffb-4e7e-b7e6-2ec35765559e' -or $manifest.formation_commit -cne '001c75ad761d6890c29db793d6d133bdcca037b8' -or $manifest.formation_parent -cne '40b20537cbe8fbd143bb3298ea92ca8b77f46c33' -or $manifest.branch -cne 'codex/self-hosted-corpus'){throw 'private permit bridge publication identity differs'}
if(@($manifest.artifacts).Count -ne 14){throw 'private permit bridge publication artifact count differs'}
$seen=@{};foreach($artifact in $manifest.artifacts){$relative=[string]$artifact.path;if([IO.Path]::IsPathRooted($relative) -or $relative.Contains('\') -or $relative -match '(^|/)[.][.](/|$)'){throw 'private permit bridge publication coordinate differs'};$key=$relative.ToUpperInvariant();if($seen.ContainsKey($key)){throw 'private permit bridge publication duplicate coordinate'};$seen[$key]=$true;$item=Get-Item -LiteralPath (Join-Path $rootPath $relative) -Force;if($item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -or $item.Length -ne [int64]$artifact.bytes -or (Get-FileHash -Algorithm SHA256 -LiteralPath $item.FullName).Hash -cne [string]$artifact.sha256){throw "private permit bridge publication artifact differs: $relative"}}
$v=$manifest.verification;$counts=@{artifact_count=14;formation_artifacts=23;formation_bindings=22;requirements=24;acceptance=5;isolated_refusals=15;redigested_refusals=2;permit_constructors=0;permit_issuances=0;runner_invocations=0;process_spawns=0;provider_requests=0;remote_calls=0;effects=0};foreach($key in $counts.Keys){if([int64]$v.$key -ne [int64]$counts[$key]){throw "private permit bridge publication count differs: $key"}}
foreach($key in @('powershell7_passed','windows_powershell51_passed','formation_remote_equal','provider_free_implementation_eligible_after_bookend')){if(-not [bool]$v.$key){throw "private permit bridge publication truth absent: $key"}}
foreach($key in @('live_authority_created','production_admission_constructor_authorized','live_initiation_authorized')){if([bool]$v.$key){throw "private permit bridge publication authority promoted: $key"}}
if($RequireBookend){$head=(& git -C $rootPath rev-parse HEAD).Trim();$parent=(& git -C $rootPath rev-parse HEAD^).Trim();$tracking=(& git -C $rootPath rev-parse refs/remotes/origin/codex/self-hosted-corpus).Trim();$directLine=& git -C $rootPath ls-remote origin refs/heads/codex/self-hosted-corpus;if($LASTEXITCODE -ne 0){throw 'private permit bridge direct remote query failed'};$direct=($directLine -split '\s+')[0];if($parent -cne [string]$manifest.formation_commit -or $head -cne $tracking -or $head -cne $direct){throw 'private permit bridge bookend lineage or remote equality differs'}}
"cantor_evox2_remote_preflight_private_permit_bridge_publication_evidence_verified=true artifacts=14 formation_commit=$($manifest.formation_commit) bookend_required=$([bool]$RequireBookend) constructors=0 issuances=0 runner_invocations=0 process_spawns=0 provider_requests=0 remote_calls=0 effects=0 live_authority=false"
