param([string]$Root = (Split-Path -Parent $PSScriptRoot))
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$rootPath=(Resolve-Path -LiteralPath $Root).Path
$manifest=Get-Content -LiteralPath (Join-Path $rootPath 'experiments/evox2_remote_preflight_one_shot_activation_ceremony_p0/private_permit_bridge_source_custody_evidence_manifest.json') -Raw|ConvertFrom-Json
if($manifest.profile -cne 'cantor-evox2-remote-preflight-private-permit-bridge-source-custody-evidence/0.1' -or $manifest.manifest_uuid -cne 'afe8dd4d-a923-4c5d-8889-a997a7bba928' -or $manifest.source_uuid -cne 'a28dc152-1260-4cfa-a8e8-6379f087d7a1' -or $manifest.source_snapshot_uuid -cne '750fbbb5-f72f-4816-882f-d8b0ebf1acc7' -or $manifest.predecessor_bookend -cne '80f2ef9f6eed3c797b911ba3c7f45e8d28130841'){throw 'bridge source custody identity differs'}
if(@($manifest.artifacts).Count -ne 10){throw 'bridge source custody artifact count differs'}
$seen=@{};foreach($artifact in $manifest.artifacts){$relative=[string]$artifact.path;if([IO.Path]::IsPathRooted($relative) -or $relative.Contains('\') -or $relative -match '(^|/)[.][.](/|$)'){throw 'bridge source custody coordinate differs'};$key=$relative.ToUpperInvariant();if($seen.ContainsKey($key)){throw 'bridge source custody duplicate coordinate'};$seen[$key]=$true;$item=Get-Item -LiteralPath (Join-Path $rootPath $relative) -Force;if($item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -or $item.Length -ne [int64]$artifact.bytes -or (Get-FileHash -LiteralPath $item.FullName -Algorithm SHA256).Hash -cne [string]$artifact.sha256){throw "bridge source custody artifact differs: $relative"}}
$sourcePath=Join-Path $rootPath 'source_documents/2026-09-11_evox2_remote_preflight_private_permit_bridge_p0/EVO_X2_Remote_Preflight_Private_Permit_Bridge_P0_Source.sop'
if((Get-Item $sourcePath).Length -ne 3892 -or (Get-FileHash $sourcePath -Algorithm SHA256).Hash -cne '0DF57E27D2F6EC1F7777CE68D313101DCA1E22CFFF9B710EC4D616435EE3A8CD'){throw 'bridge source identity differs'}
$v=$manifest.verification;foreach($key in @('artifact_count','source_bytes')){if([int64]$v.$key -ne $(if($key -eq 'artifact_count'){10}else{3892})){throw "bridge source count differs: $key"}};foreach($key in @('permit_constructors','runner_invocations','process_spawns','provider_requests','remote_calls','effects')){if([int64]$v.$key -ne 0){throw "bridge source effect differs: $key"}};foreach($key in @('implementation_authorized','live_initiation_authorized')){if([bool]$v.$key){throw "bridge source authority promoted: $key"}}
'cantor_evox2_remote_preflight_private_permit_bridge_source_custody_evidence_verified=true artifacts=10 source_bytes=3892 permit_constructors=0 runner_invocations=0 process_spawns=0 provider_requests=0 remote_calls=0 effects=0 implementation_authorized=false live_initiation_authorized=false'
